language: android
dist: trusty
android:
  components:
    - build-tools-29.0.0
    - android-28
    - extra-google-m2repository
    - tools
    - platform-tools

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


before_install:
  # Required to avoid unsatisfied link exceptions from ObjectBox
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6

script:
  - ./gradlew detekt test