name: "Android Test"
on:
  push:

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          emulator-options: ""
          script: "./gradlew connectedCheck test detekt"
      
      - name: upload failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: build-artifact
          path: app/build